services:
  app:
    image: ${APP_IMAGE}

    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailer:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: Europe/Kyiv

      MYSQL_HOST: db
      MYSQL_DATABASE: rating
      MYSQL_USER: rating_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_URL: mysql://rating_user:${MYSQL_PASSWORD}@db:3306/rating?charset=utf8mb4
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      APP_SHARE_DIR: var/share
      DEFAULT_URI: ${DEFAULT_URI}
      REDIS_URL: redis://redis:6379/1
      REDIS_SESSION_URL: redis://redis:6379/2
      REDIS_RATE_LIMITER_URL: redis://redis:6379/3
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      MAILER_DSN: smtp://mailer:1025
      VAR_DUMPER_SERVER: 127.0.0.1:9912

  db:
    image: mysql:9.3
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Kyiv
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: rating
      MYSQL_USER: rating_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db_data:
  redis_data:
