# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    app.upload_dir: '%kernel.project_dir%/var/uploads/tournament_documents'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Mapping\MappingInterface:
            tags: ['app.mapping']

    App\:
        resource: '../src/'

    App\Mapping\Mapper:
        arguments:
            $mappings: !tagged_iterator app.mapping

    App\Service\TournamentDocumentService:
        arguments:
            $uploadDir: '%app.upload_dir%'

when@dev: &dev_fixtures
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\DataFixtures\:
            resource: '../tests/DataFixtures/'

when@test: *dev_fixtures
